on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v0.0.18
        id: snake-gif
        with:
          github_user_name: lintzuyun
          svg_out_path: dist/github-snake.svg
        # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
